configuration:
  activeRevisionsMode: Single
  ingress:
    external: true
    targetPort: 4000
template:
  containers:
  - image: ghcr.io/heddendorp/tumi/events:main
    name: tumi-events
    env:
    - name: NODE_ENV
      value: production
    - name: PM2_PUBLIC_KEY
      value: dlasc229vo4thbf
    - name: PM2_SECRET_KEY
      secretRef: pm2-secret-key
    resources:
      cpu: 1
      memory: 2Gi
  scale:
    minReplicas: 0
    maxReplicas: 5
    rules:
      - name: http-rule
        http:
          metadata:
            concurrentRequests: 300
      - name: cpu-scaling-rule
        custom:
          type: cpu
          metadata:
            type: Utilization
            value: 80
