configuration:
  activeRevisionsMode: Single
  ingress:
    external: true
    targetPort: 3333
template:
  containers:
  - image: ghcr.io/heddendorp/tumi/server:main
    name: tumi-server
    env:
    - name: DATABASE_URL
      secretRef: database-url
    - name: NODE_ENV
      value: production
    - name: HIVE_TOKEN
      secretRef: hive-token
    - name: SENDGRID_API_KEY
      secretRef: sendgrid-key
    - name: STRIPE_KEY
      secretRef: stripe-key
    - name: STRIPE_WH_SECRET
      secretRef: stripe-wh-secret
    resources:
      cpu: 1
      memory: 2Gi
  scale:
    minReplicas: 0
    maxReplicas: 5
    rules:
    - name: http-rule
      http:
        metadata:
          concurrentRequests: 300
    - name: cpu-scaling-rule
      custom:
        type: cpu
        metadata:
          type: Utilization
          value: 80
